pipeline:
  name: Nginx-pipeline
  identifier: Nginxpipeline
  projectIdentifier: Manisha
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Bg-Deploy
        identifier: BgDeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: harnessguestbook
          environment:
            environmentRef: harnessdevenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfra
          execution:
            steps:
              - step:
                  name: Stage Deployment
                  identifier: stageDeployment
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  name: Swap primary with stage service
                  identifier: bgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
              - step:
                  type: K8sBlueGreenStageScaleDown
                  name: K8sBlueGreenStageScaleDown_1
                  identifier: K8sBlueGreenStageScaleDown_1
                  spec:
                    deleteResources: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
